/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-01-08 17:48:37 UTC)
 * on 2016-01-15 at 07:02:12 UTC 
 * Modify at your own risk.
 */

package com.appspot.progress_1181.progressApi;

/**
 * Service definition for ProgressApi (v1).
 *
 * <p>
 * Monitor any progress.
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ProgressApiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class ProgressApi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the progressApi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://progress-1181.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "progressApi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public ProgressApi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  ProgressApi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "create".
   *
   * This request holds the parameters needed by the progressApi server.  After setting any optional
   * parameters, call the {@link Create#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.progress_1181.progressApi.model.ProgressModelsCreateProgressRequestMessage}
   * @return the request
   */
  public Create create(com.appspot.progress_1181.progressApi.model.ProgressModelsCreateProgressRequestMessage content) throws java.io.IOException {
    Create result = new Create(content);
    initialize(result);
    return result;
  }

  public class Create extends ProgressApiRequest<com.appspot.progress_1181.progressApi.model.ProgressModelsCreateProgressResponseMessage> {

    private static final String REST_PATH = "create";

    /**
     * Create a request for the method "create".
     *
     * This request holds the parameters needed by the the progressApi server.  After setting any
     * optional parameters, call the {@link Create#execute()} method to invoke the remote operation.
     * <p> {@link
     * Create#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.progress_1181.progressApi.model.ProgressModelsCreateProgressRequestMessage}
     * @since 1.13
     */
    protected Create(com.appspot.progress_1181.progressApi.model.ProgressModelsCreateProgressRequestMessage content) {
      super(ProgressApi.this, "POST", REST_PATH, content, com.appspot.progress_1181.progressApi.model.ProgressModelsCreateProgressResponseMessage.class);
    }

    @Override
    public Create setAlt(java.lang.String alt) {
      return (Create) super.setAlt(alt);
    }

    @Override
    public Create setFields(java.lang.String fields) {
      return (Create) super.setFields(fields);
    }

    @Override
    public Create setKey(java.lang.String key) {
      return (Create) super.setKey(key);
    }

    @Override
    public Create setOauthToken(java.lang.String oauthToken) {
      return (Create) super.setOauthToken(oauthToken);
    }

    @Override
    public Create setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Create) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Create setQuotaUser(java.lang.String quotaUser) {
      return (Create) super.setQuotaUser(quotaUser);
    }

    @Override
    public Create setUserIp(java.lang.String userIp) {
      return (Create) super.setUserIp(userIp);
    }

    @Override
    public Create set(String parameterName, Object value) {
      return (Create) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "delete".
   *
   * This request holds the parameters needed by the progressApi server.  After setting any optional
   * parameters, call the {@link Delete#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.progress_1181.progressApi.model.ProgressModelsDeleteProgressRequestMessage}
   * @return the request
   */
  public Delete delete(com.appspot.progress_1181.progressApi.model.ProgressModelsDeleteProgressRequestMessage content) throws java.io.IOException {
    Delete result = new Delete(content);
    initialize(result);
    return result;
  }

  public class Delete extends ProgressApiRequest<Void> {

    private static final String REST_PATH = "delete";

    /**
     * Create a request for the method "delete".
     *
     * This request holds the parameters needed by the the progressApi server.  After setting any
     * optional parameters, call the {@link Delete#execute()} method to invoke the remote operation.
     * <p> {@link
     * Delete#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.progress_1181.progressApi.model.ProgressModelsDeleteProgressRequestMessage}
     * @since 1.13
     */
    protected Delete(com.appspot.progress_1181.progressApi.model.ProgressModelsDeleteProgressRequestMessage content) {
      super(ProgressApi.this, "POST", REST_PATH, content, Void.class);
    }

    @Override
    public Delete setAlt(java.lang.String alt) {
      return (Delete) super.setAlt(alt);
    }

    @Override
    public Delete setFields(java.lang.String fields) {
      return (Delete) super.setFields(fields);
    }

    @Override
    public Delete setKey(java.lang.String key) {
      return (Delete) super.setKey(key);
    }

    @Override
    public Delete setOauthToken(java.lang.String oauthToken) {
      return (Delete) super.setOauthToken(oauthToken);
    }

    @Override
    public Delete setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Delete) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Delete setQuotaUser(java.lang.String quotaUser) {
      return (Delete) super.setQuotaUser(quotaUser);
    }

    @Override
    public Delete setUserIp(java.lang.String userIp) {
      return (Delete) super.setUserIp(userIp);
    }

    @Override
    public Delete set(String parameterName, Object value) {
      return (Delete) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "generateNewApiKey".
   *
   * This request holds the parameters needed by the progressApi server.  After setting any optional
   * parameters, call the {@link GenerateNewApiKey#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GenerateNewApiKey generateNewApiKey() throws java.io.IOException {
    GenerateNewApiKey result = new GenerateNewApiKey();
    initialize(result);
    return result;
  }

  public class GenerateNewApiKey extends ProgressApiRequest<com.appspot.progress_1181.progressApi.model.ProgressModelsUserResponseMessage> {

    private static final String REST_PATH = "generateNewApiKey";

    /**
     * Create a request for the method "generateNewApiKey".
     *
     * This request holds the parameters needed by the the progressApi server.  After setting any
     * optional parameters, call the {@link GenerateNewApiKey#execute()} method to invoke the remote
     * operation. <p> {@link GenerateNewApiKey#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GenerateNewApiKey() {
      super(ProgressApi.this, "GET", REST_PATH, null, com.appspot.progress_1181.progressApi.model.ProgressModelsUserResponseMessage.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GenerateNewApiKey setAlt(java.lang.String alt) {
      return (GenerateNewApiKey) super.setAlt(alt);
    }

    @Override
    public GenerateNewApiKey setFields(java.lang.String fields) {
      return (GenerateNewApiKey) super.setFields(fields);
    }

    @Override
    public GenerateNewApiKey setKey(java.lang.String key) {
      return (GenerateNewApiKey) super.setKey(key);
    }

    @Override
    public GenerateNewApiKey setOauthToken(java.lang.String oauthToken) {
      return (GenerateNewApiKey) super.setOauthToken(oauthToken);
    }

    @Override
    public GenerateNewApiKey setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GenerateNewApiKey) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GenerateNewApiKey setQuotaUser(java.lang.String quotaUser) {
      return (GenerateNewApiKey) super.setQuotaUser(quotaUser);
    }

    @Override
    public GenerateNewApiKey setUserIp(java.lang.String userIp) {
      return (GenerateNewApiKey) super.setUserIp(userIp);
    }

    @Override
    public GenerateNewApiKey set(String parameterName, Object value) {
      return (GenerateNewApiKey) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "list".
   *
   * This request holds the parameters needed by the progressApi server.  After setting any optional
   * parameters, call the {@link List#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public List list() throws java.io.IOException {
    List result = new List();
    initialize(result);
    return result;
  }

  public class List extends ProgressApiRequest<com.appspot.progress_1181.progressApi.model.ProgressModelsQueryProgressResponseMessage> {

    private static final String REST_PATH = "list";

    /**
     * Create a request for the method "list".
     *
     * This request holds the parameters needed by the the progressApi server.  After setting any
     * optional parameters, call the {@link List#execute()} method to invoke the remote operation. <p>
     * {@link List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected List() {
      super(ProgressApi.this, "GET", REST_PATH, null, com.appspot.progress_1181.progressApi.model.ProgressModelsQueryProgressResponseMessage.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public List setAlt(java.lang.String alt) {
      return (List) super.setAlt(alt);
    }

    @Override
    public List setFields(java.lang.String fields) {
      return (List) super.setFields(fields);
    }

    @Override
    public List setKey(java.lang.String key) {
      return (List) super.setKey(key);
    }

    @Override
    public List setOauthToken(java.lang.String oauthToken) {
      return (List) super.setOauthToken(oauthToken);
    }

    @Override
    public List setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (List) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public List setQuotaUser(java.lang.String quotaUser) {
      return (List) super.setQuotaUser(quotaUser);
    }

    @Override
    public List setUserIp(java.lang.String userIp) {
      return (List) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String pageToken;

    /**

     */
    public java.lang.String getPageToken() {
      return pageToken;
    }

    public List setPageToken(java.lang.String pageToken) {
      this.pageToken = pageToken;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String apikey;

    /**

     */
    public java.lang.String getApikey() {
      return apikey;
    }

    public List setApikey(java.lang.String apikey) {
      this.apikey = apikey;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long limit;

    /**
   [ default: 10]
   [

     */
    public java.lang.Long getLimit() {
      return limit;
    }

    public List setLimit(java.lang.Long limit) {
      this.limit = limit;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String order;

    /**
   [ default: -lastUpdated]
   [

     */
    public java.lang.String getOrder() {
      return order;
    }

    public List setOrder(java.lang.String order) {
      this.order = order;
      return this;
    }

    @Override
    public List set(String parameterName, Object value) {
      return (List) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "update".
   *
   * This request holds the parameters needed by the progressApi server.  After setting any optional
   * parameters, call the {@link Update#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.progress_1181.progressApi.model.ProgressModelsUpdateProgressRequestMessage}
   * @return the request
   */
  public Update update(com.appspot.progress_1181.progressApi.model.ProgressModelsUpdateProgressRequestMessage content) throws java.io.IOException {
    Update result = new Update(content);
    initialize(result);
    return result;
  }

  public class Update extends ProgressApiRequest<Void> {

    private static final String REST_PATH = "update";

    /**
     * Create a request for the method "update".
     *
     * This request holds the parameters needed by the the progressApi server.  After setting any
     * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
     * <p> {@link
     * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.progress_1181.progressApi.model.ProgressModelsUpdateProgressRequestMessage}
     * @since 1.13
     */
    protected Update(com.appspot.progress_1181.progressApi.model.ProgressModelsUpdateProgressRequestMessage content) {
      super(ProgressApi.this, "POST", REST_PATH, content, Void.class);
    }

    @Override
    public Update setAlt(java.lang.String alt) {
      return (Update) super.setAlt(alt);
    }

    @Override
    public Update setFields(java.lang.String fields) {
      return (Update) super.setFields(fields);
    }

    @Override
    public Update setKey(java.lang.String key) {
      return (Update) super.setKey(key);
    }

    @Override
    public Update setOauthToken(java.lang.String oauthToken) {
      return (Update) super.setOauthToken(oauthToken);
    }

    @Override
    public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Update) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Update setQuotaUser(java.lang.String quotaUser) {
      return (Update) super.setQuotaUser(quotaUser);
    }

    @Override
    public Update setUserIp(java.lang.String userIp) {
      return (Update) super.setUserIp(userIp);
    }

    @Override
    public Update set(String parameterName, Object value) {
      return (Update) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "userProfile".
   *
   * This request holds the parameters needed by the progressApi server.  After setting any optional
   * parameters, call the {@link UserProfile#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public UserProfile userProfile() throws java.io.IOException {
    UserProfile result = new UserProfile();
    initialize(result);
    return result;
  }

  public class UserProfile extends ProgressApiRequest<com.appspot.progress_1181.progressApi.model.ProgressModelsUserResponseMessage> {

    private static final String REST_PATH = "userProfile";

    /**
     * Create a request for the method "userProfile".
     *
     * This request holds the parameters needed by the the progressApi server.  After setting any
     * optional parameters, call the {@link UserProfile#execute()} method to invoke the remote
     * operation. <p> {@link
     * UserProfile#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected UserProfile() {
      super(ProgressApi.this, "GET", REST_PATH, null, com.appspot.progress_1181.progressApi.model.ProgressModelsUserResponseMessage.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public UserProfile setAlt(java.lang.String alt) {
      return (UserProfile) super.setAlt(alt);
    }

    @Override
    public UserProfile setFields(java.lang.String fields) {
      return (UserProfile) super.setFields(fields);
    }

    @Override
    public UserProfile setKey(java.lang.String key) {
      return (UserProfile) super.setKey(key);
    }

    @Override
    public UserProfile setOauthToken(java.lang.String oauthToken) {
      return (UserProfile) super.setOauthToken(oauthToken);
    }

    @Override
    public UserProfile setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UserProfile) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UserProfile setQuotaUser(java.lang.String quotaUser) {
      return (UserProfile) super.setQuotaUser(quotaUser);
    }

    @Override
    public UserProfile setUserIp(java.lang.String userIp) {
      return (UserProfile) super.setUserIp(userIp);
    }

    @Override
    public UserProfile set(String parameterName, Object value) {
      return (UserProfile) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link ProgressApi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link ProgressApi}. */
    @Override
    public ProgressApi build() {
      return new ProgressApi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ProgressApiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setProgressApiRequestInitializer(
        ProgressApiRequestInitializer progressapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(progressapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
