application: progress-1181
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
  # Endpoints handler: Must be /_ah/spi. Apps send requests to /_ah/api, but these are handled at /_ah/spi!!
- url: /_ah/spi/.*
  script: progress_api.APPLICATION

- url: /(.+)
  static_files: static/\1
  upload: static/(.*)

- url: /
  static_files: static/index.html
  upload: static/index.html


libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
