application: progress-1181
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /js/(.+)
  static_files: www/js/\1
  upload: www/js/(.+)

- url: /vendor/(.+)
  static_files: www/vendor/\1
  upload: www/vendor/(.+)

- url: /views/(.+)
  static_files: www/views/\1
  upload: www/views/(.+)

  # Endpoints handler: Must be /_ah/spi. Apps send requests to /_ah/api, but these are handled at /_ah/spi!!
- url: /_ah/spi/.*
  script: endpoint_services.APPLICATION
  secure: always

- url: /(.+)
  static_files: www/index.html
  upload: www/index.html
  secure: always

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
